#!/usr/bin/env python
"""
A description of the plugin.

Usage:
  plugin1 [options] (command1 | command2 ARG)

Arguments:
  ARG  an arg

Options:
  --aaa    sdfdsf
  --qqq    dfdfdf
  -d

"""

import sys

def main(args):
    print(args)
    if args['--aaa']: print("Ran with AAA option")
    if args['--qqq']: print("Ran with QQQ option")

    if args['command1']:
        print("Executing command1")
    elif args['command2']:
        print(f"Executing command2 with {args['ARG']} ARG")

if __name__ == '__main__':
    from docopt import docopt
    args = docopt(__doc__)
    main(args)
